### PR TITLE
Fix N+1 query issue wrt feedback index page for admins

### PR DESCRIPTION
**Pull request by boddhisattva**

### CODE REVIEW

**Comment by boddhisattva** [comment]
Just rebased this branch on top of latest master.

**Comment by marten** [comment]
Hi, thanks for your help! Look good to me.

**Comment by matyikriszta** [comment]
this seems to be out of date again :( sorry, it was me, I merged in a bunch if stuff this morning. let me know if you can rebase one more time @boddhisattva or I can do it for you :)

**Comment by boddhisattva** [comment]
@matyikriszta no worries :) Just did a rebase.

**Pull request merged**
