### PR TITLE
Add Community partner option to Sponsor levels

### LINKED ISSUE #1492: Add "Community Partner" sponsorship option
## Description of the issue 📄
On our Sponsors page (https://codebar.io/sponsors) we have the option to add `Gold`, `Silver` and `Bronze` levels. We would like to add another option, `Community Partner`.

## To do 📋

* [x] Claim this issue (comment below, or assign yourself if you are part of the codebar org)
* [ ] Fork and clone the repository
* [ ] Update the relevant files. Follow the steps to fix section in this issue.
* [ ] Commit your changes as one commit. Use the title of this issue as your commit message
* [ ] Submit a pull request
* [ ] Mention this issue in the PR description by including it's number
* [ ] Have your pull request reviewed & merged by a codebar team member

### PR DESCRIPTION
**Pull request by matyikriszta**
## Description
This PR adds the Community partner option to Sponsor levels.

## Status
Ready for Review

## Screenshots
Screenshot 2021-03-25 at 9 11 43 pm

## Related Github issue
Fixes #1492

### CODE REVIEW

**Review by despo — APPROVED** [review]
Thanks for doing this @matyikriszta

**Comment by gnclmorais** [comment]
This might help with the failing test (we’re getting into British Summer Time in a couple of days, so we moved from GMT+00:00 to GMT+01:00):
```diff
diff --git a/spec/features/admin/event_spec.rb b/spec/features/admin/event_spec.rb
index 73ebb57c..5165a51c 100644
--- a/spec/features/admin/event_spec.rb
+++ b/spec/features/admin/event_spec.rb
@@ -32,7 +32,7 @@ RSpec.feature 'Event creation', type: :feature do
         expect(page).to have_content('Event successfully created')

         expect(page).to have_content('A test event')
-        expect(page).to have_content("#{I18n.l(date, format: :humanised)} | 16:00 - 18:00 GMT (GMT+00:00)")
+        expect(page).to have_content(humanize_date(date))
         expect(page).to have_content('A test event description')
         expect(page).to have_content('25 student spots, 19 coach spots')
         expect(find('#schedule', visible: false).text).to eq('9:00 Sign up & breakfast 9:30 kick off')
```

**Comment by matyikriszta** [comment]
> ```diff
> humanize_date(date)
> ```

Thanks @gnclmorais, that worked

**Comment by KimberleyCook** [comment]
Amazing, thanks for doing this @matyikriszta

**Pull request merged**
