### PR TITLE
Add and configure rubocop #codebar24PR2017

### PR DESCRIPTION
**Pull request by bellvat**
Hi @matyikriszta 

PR for Issue#635

- Added the Rubocop Gem
- Added rubocop configuration file .rubocop.yml at root directory
  - As discussed, disabled rubocop for 1.Missing top level comments 2.Frozen string literals
- Fixing `Line length Exceeding 80 chars`offenses would involve refactoring code into two lines, which might be better suited for someone more familiar with the code base
- Ran auto-correct for various Layout and Style cops using the following command: `rubocop --only <cop name> -a`
  - `Single quote preferred over double quote` offenses were corrected
  - Auto-correct brought down offenses from 3,800 to 1,254 offenses

### CODE REVIEW

**Comment by skattyadz** [comment]
Great! This will help us with a consistent style.

I'm happy with the code here, but should we add something to the readme to make sure it gets used?

Personally, I think 80 chars is a bit tight, but people could argue on that one all day!

**Comment by matyikriszta** [comment]
@skattyadz I agree about adding a note to the README about running rubocop before one creates a PR.

**Comment by skattyadz** [comment]
I think it's just as important to have it in your editor as you're going
along. Getting that feedback late is frustrating and might be combined with
existing errors in the codebase. Unless we encourage lint-staged and
similar

Is there a PR checklist?

**Comment by bellvat** [comment]
Hi @matyikriszta 
I added a line to run Rubocop in Contributing.md.
Please let me know if the wording is okay or if any changes are needed.

**Comment by matyikriszta** [comment]
@skattyadz I agree but good luck getting everyone to install it in their editors. I think as long as we make it a requirement for merge people will do it (no other choice haha). I do not have a PR checklist yet but will put together one in the near future

**Comment by matyikriszta** [comment]
@bellvat yes, wording looks good to me. I'm happy to merge this in.

**Comment by skattyadz** [comment]
I don't think k we should require it in your editor! Just explain that
you're going to have a less frustrating time if you see those errors early

Also, should rubocop be in the test section of the gentile?

**Pull request merged**
