### PR TITLE
Updates to text around the sign up process

### PR DESCRIPTION
**Pull request by BNewing**
At the moment, the codebar.io/chaptername page is the first page that our codebar Oxford posters direct to. That page doesn't have very much information on it, so I've added in some text which directs people to the FAQ page and clarifies things a bit:

image

I've also added some text about GitHub onto the second page of the sign up process to warn people that they're about to leave the codebar site, just in case the transition is unnerving. I've chosen to not include a link to GitHub here because they'll be taken there anyway.

image

Feel free to suggest changes to the wording; I'm a bit sleepy at the time of writing them. 

#599

### CODE REVIEW

**Comment by KimberleyCook** [comment]
@BNewing this is so great thank you, once Travis passes I'll merge in 😁

**Comment by BNewing** [comment]
Thanks @KimberleyCook ! I've checked the Travis build fail details and it looks like it's something to do with the jobs stuff, but I've no idea how to fix it. Do you have any idea what might be causing that?

**Comment by marten** [comment]
That test failure is unrelated. It's due to the job fabricator choosing job titles at random, and thus sometimes choosing duplicate ones, and in that case Capybara can no longer tell which link to click on (and thus errors). I'll make a PR to fix that, but I suggest we ignore the failing test and merge this if it's good to go.

**Comment by KimberleyCook** [comment]
Wooo Travis likes us. Thanks so much for this @BNewing 😁

**Pull request merged**
