### PR TITLE
Add counter for signed-in workshop attendees

### PR DESCRIPTION
**Pull request by MarckK**

### CODE REVIEW

**Comment by MarckK** [comment]
I can change the green color, as desired. :)

**Comment by MarckK** [comment]
screen shot 2018-10-04 at 08 30 10

**Comment by richardwestenra** [comment]
@MarckK Just saw the email for this! I'm delighted that you've added this feature, thank you soooo much! 😄 👯‍♂️ 🎉

**Comment by despo** [comment]
@MarckK deployed! :shipit:

**Comment by MarckK** [comment]
Sweet! Thank you, @despo, @richardwestenra, @matyikriszta 😄

**Pull request merged**
