### PR TITLE
Update copyright to 2018

### PR DESCRIPTION
**Pull request by minaorangina**
Currently still reads as copyright 2017 :)

### CODE REVIEW

**Comment by KimberleyCook** [comment]
@minaorangina Is there some way in Rails this could be automated??

**Comment by BPScott** [comment]
```
 &#169; #{Date.today.year} codebar 
```
Seems like it would work

**Comment by KimberleyCook** [comment]
@BPScott exactly what I was after!

@minaorangina Are you able to make the above amend please? :)

**Comment by minaorangina** [comment]
@KimberleyCook @BPScott sure, I'll add it

**Pull request merged**
