### PR TITLE
Fix Menu dropdown layout issues & upgrade Bootstrap to latest version

### LINKED ISSUE #1521: Menu nav item dropdown is cut off by the edge of the screen on desktop
There are a couple of layout issues in the main navigation Menu item dropdown:
- a few items are missing the `dropdown-item` class
- on large viewports the right side of the dropdown is cut off by the edge of the screen
- the dropdown is too long when it includes admin menu items. Even on large viewports the bottom of the screen cuts off a few menu items at the bottom (including the Sign out link)

Screenshot 2021-04-30 at 4 45 41 pm

### PR DESCRIPTION
**Pull request by matyikriszta**
## Description
This PR fixes a few layout issues in the Menu dropdown:
- ensures the dropdown is right aligned compared to the trigger
- fixes broken links within dropdown
- splits the member and admin menus into two dropdown to avoid the screen cutting off dropdown items

## Status
Work in Progress

## Related Github issue
Fixes #1521 

## Screenshots
Menu dropdown Before | Menu dropdown After
------------ | -------------
Screenshot 2021-04-30 at 4 45 41 pm | Screenshot 2021-05-03 at 5 18 27 pm Screenshot 2021-05-03 at 5 18 40 pm

### CODE REVIEW

**Review by KimberleyCook — COMMENTED** [review]
Are we moving to single quotes in the codebase?

**Comment by matyikriszta** [comment]
> Are we moving to single quotes in the codebase?

@KimberleyCook honestly I don't mind, I just want to standardize on one st of quotes. I've been using single quotes because in .rb files it's the suggested style. But happy to decide on double quote for .html files.

**Comment by gnclmorais** [comment]
I would like to see the use of single or double quotes standardised as well (although I have a small preference for double quotes in Ruby, since this way I don’t ever need to thing if I need string interpolation or not, reducing the possibility of bugs in my opinion).

**Comment by despo** [comment]
We should use single quotes for strings and double quotes in case of interpolation as it's quite a standard Ruby practise. 

Also, we should aim for double quotes for html files - however I've never used a haml linter nor do I know how much effort may be required to setup one and it's definitely low priority! 



use single quote literals for your strings and go for the double ones in the case of interpolation/escaping sequences.

**Comment by matyikriszta** [comment]
Closing this PR as it's very out of date with the base branch (and I cannot be bothered to rebase). Going to open a new PR with this work.

**Pull request closed without merging**
