### PR TITLE
Drop meetings and meeting talks

### PR DESCRIPTION
**Pull request by stschwark**
I ran into errors when setting up the planner locally on my machine due to the issues with meetings / meeting_talks described in #319. This pull request removes Meetings, MeetingTalks and any references. It doesn't include refactoring Sessions into Workshops, etc. as also proposed in #319.

### CODE REVIEW

**Comment by despo** [comment]
@stschwark after merging an older pending PR there are are some issues that need to be resolved on this branch before I can merge. Guessing it will be resolved by just regenerating the scema.

**Comment by stschwark** [comment]
@despo rebased

**Comment by asuffield** [comment]
Can we get this one merged?

**Comment by despo** [comment]
So, I am keen in merging this. However, I dont want to delete any of our data.

Will open a relevant issue.

**Comment by despo** [comment]
On hold until https://github.com/codebar/planner/issues/372

**Comment by deniseyu** [comment]
I've reappropriated meetings to use for codebar Monthlies. I haven't deleted meeting talks but have removed them from the views and seeds, so they should pose no problem in setting up the app now.

**Pull request closed without merging**
