### PR TITLE
Use thumb version of sponsor avatar

### PR DESCRIPTION
**Pull request by matyikriszta**
This PR is a potential fix for #534. The sponsor avatar uploader had a thumb size defined but we were not making use of it in the templates.

### CODE REVIEW

**Comment by conorcussell** [comment]
@matyikriszta yep - that should fix it. I was unable to test locally when I opened the issue because carrierwave is not enabled when developing locally. Do you have a staging server we can check it on?

**Comment by matyikriszta** [comment]
@conorcussell yes, we can push it up to staging an see if it fixes the issue. Got to first fix all of the failing tests

**Comment by conorcussell** [comment]
Let me know if you want help? Happy to take a look now if you do!

**Comment by matyikriszta** [comment]
@conorcussell that would be great, thanks! I have tried a few things and nothing worked so far :) But the problem seems to be related to this article: https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Use-test-factories

**Comment by conorcussell** [comment]
@matyikriszta to be honest I'd be inclined to do something like this in the template.

```ruby
- if (sponsor.avatar.respond_to?(:thumb))
  = image_tag sponsor.avatar.thumb, class: 'sponsor'
- else
  = image_tag sponsor.avatar, class: 'sponsor'
```

I couldn't find any way of mocking different image sizes! Someone might have a better idea, but I don't see any real issue with this. Bare in mind I haven't been writing any rails code for at least a year though...

**Comment by despo** [comment]
@matyikriszta  I've had a look at this and to resolve the failures we need to make the following changes:

https://github.com/codebar/planner/blob/master/app/models/sponsor.rb#L15 
Make uploader available in any environment, not just production

```ruby
 mount_uploader(:avatar, AvatarUploader) 
```
https://github.com/codebar/planner/blob/master/spec/fabricators/sponsor_fabricator.rb#L11
Update sponsor fabricator to associate an uploaded image with the avatar
```ruby
  avatar { Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', 'logo.png'), 'image/jpeg') }
```

https://github.com/codebar/planner/blob/master/spec/models/sponsor_spec.rb#L40
Set the subject to a new factory with a nil image as setting the image to nil, won't update it.
```ruby
subject(:sponsor) { Fabricate.build(:sponsor, avatar: nil) }
```
https://github.com/codebar/planner/blob/master/spec/controllers/admin/sponsors_controller_spec.rb#L8
Set the avatar to an uploaded image.
```ruby
 let(:avatar) { Rack::Test::UploadedFile.new(Rails.root.join('app', 'assets', 'images', 'logo.png'), 'image/jpeg') }
```

**Comment by matyikriszta** [comment]
@despo thanks for looking into this, just testing this now

**Pull request merged**
