### PR TITLE
Remove redundant self

### PR DESCRIPTION
**Pull request by notapatch**
- prefer removing redundant self
 - auto-corrected
   rubocop -a --only=Style/RedundantSelf

---

If any of these Rubocops aren't liked I can update the rubocop.yml appropriately.

### CODE REVIEW

**Comment by notapatch** [comment]
@despo if at all possible I would keep Rubocop commits as fixing the one class of problem.

```
# 1 issue to fix
Avoid using rescue in its modifier form. New

    WorkshopSponsor.hosts.for_workshop(id).first.sponsor rescue nil

Severity: Minor
Found in app/models/workshop.rb by rubocop
```

**Comment by despo** [comment]
@notapatch can we have a separate commit for the other fix then? 
I know it's a bit frustrating when new issues come up just because you've modified other bits of code on the line but even though in an ideal world we would tackle each issue separately, the reality is that we are more likely to attempt to resolve them as part of other work.

**Comment by notapatch** [comment]
Needed to make a change to `Workshop#host ` but I didn't understand the code (never used rescue in a one-liner). The code relied on WorkshopSponsor so I tested that before finally looking at Workshop#host.

I didn't use the Rubocop 'fix' because I wanted to avoid using exceptions in the normal flow of the code, if possible, and safe navigation offered that solution.

**Comment by despo** [comment]
@notapatch looks good. The code just mean that t if an exception was thrown at any point in that call, so for example if there are no sponsors set as hosts on the workshop at all and thus `[].first` responds with `nil` when `[].first.sponsor` fails and throws an exception it catches it and returns `nil` instead.

It was also put in place long before the safe navigation operator was introduced (or maybe before it started being common in Ruby and reccommended for use).

**Pull request merged**
