### PR TITLE
Sidemenu is not sticky

### PR DESCRIPTION
**Pull request by GarySiu**
A workaround implementation for #1021

- removes `overflow: hidden` from various places
- sticky positions the contents of the off-canvas menu

### CODE REVIEW

**Comment by notapatch** [comment]
Hi @GarySiu,

I promise if you rebase you will not get that Travis error again.

**Comment by GarySiu** [comment]
Thanks for resolving the CI issues!

**Comment by GarySiu** [comment]
Leaving a comment so this isn't marked as stale. As far as I know, this can still be merged.

**Comment by matyikriszta** [comment]
@GarySiu we are working on a PR that should go live soon that is going to remove the sticky sidebar so going to close this PR regardless. Thanks for your contribution and sorry we did not merge this in earlier.

**Pull request closed without merging**
