### PR TITLE
Remove job board code

### PR DESCRIPTION
**Pull request by KimberleyCook**
Remove a load of job board code, and I've updated URL in places.

### CODE REVIEW

**Comment by matyikriszta** [comment]
@KimberleyCook the Tests checks are failing because Rails is trying to run a migration that updates Job, but Job does not exists anymore. I checked locally and you should be able to remove the migration file `db/migrate/20181013230006_update_job_statuses.rb`.

**Comment by KimberleyCook** [comment]
@matyikriszta all done, 🤞 this works. Thanks

**Review by matyikriszta — APPROVED** [review]
Tentative 🎉, let's see how this deploys first 😂

**Comment by KimberleyCook** [comment]
@matyikriszta you saying I can merge? 😅

**Comment by matyikriszta** [comment]
Yes, let's merge

**Comment by KimberleyCook** [comment]
@matyikriszta 🤞 ha

**Pull request merged**
