### PR TITLE
fixing the go squared image in the footer

### PR DESCRIPTION
**Pull request by markdessain**
Issue: #539 

Fixes the missing GoSqaured image.

screen shot 2017-04-10 at 21 23 10

I found the original image we used on the Wayback Machine and placed it in the assets rather than relying on an extra dropbox account.

### CODE REVIEW

**Comment by BPScott** [comment]
I'd be kinda tempted to delete that image reference (and the whole row that contains it) entirely - it seems to be noise.

**Comment by matyikriszta** [comment]
hey @markdessain thanks for taking a look at this. I agree with @BPScott, we don't really use this service anymore, could we just remove the image + row?

**Comment by markdessain** [comment]
@matyikriszta @BPScott - done

**Comment by matyikriszta** [comment]
@markdessain 👍 I'll merge once all the check have passed

**Comment by matyikriszta** [comment]
awesome, thanks @markdessain

**Pull request merged**
