### PR TITLE
Bootstrap Sign up step 1

### PR DESCRIPTION
**Pull request by KimberleyCook**
Not much has changed here, I have deleted a load of divs that I don't think were required anymore.

screencapture-localhost-3000-member-details-edit-2020-11-26-17_04_16

### CODE REVIEW

**Comment by matyikriszta** [comment]
@KimberleyCook can we try aligning the form with the heading and subheading text on the page? I think it would look better that way (rather then center aligned).

**Comment by KimberleyCook** [comment]
@matyikriszta yeah good shout. Will do this today

**Comment by KimberleyCook** [comment]
@matyikriszta all done :)

**Comment by matyikriszta** [comment]
@KimberleyCook nice one, looks good to go 👍

**Review by matyikriszta — APPROVED** [review]

**Pull request merged**
