### PR TITLE
Localise invitation meeting messages

### PR DESCRIPTION
**Pull request by notapatch**

### CODE REVIEW

**Comment by despo** [comment]
@notapatch Unfortunately this got caught in the middle of the dependabot merges. Do you have time to rebase? If not let me know and can pick it up!

**Comment by notapatch** [comment]
Hopefully that's rebased. I say hopefully because although I can see the last branch on my local system is correct (Bump rubocop from 0.79.0 to 0.80.1) I don't know how to see the remote's pr 'base'.

**Comment by despo** [comment]
@notapatch This is correctly rebased. The PR's base would be the master branch, but github would have also displayed additional unintentional changes in the *File changes* tab (and the built would have likely failed) if something went wrong.

**Comment by notapatch** [comment]
@despo thanks for the explanation. I'll look out for it next time 👍

**Pull request merged**
