### PR TITLE
Upgrade to Rails 5.0.7.2 💎🆙

### PR DESCRIPTION
**Pull request by gnclmorais**
Version 4.2 was released in [2014](https://en.wikipedia.org/wiki/Ruby_on_Rails#History) so our Rails version is a bit behind. Upgrading straight to 6.0 (current Rails version) doesn’t seem like a good way to do things, too many changes accumulate — so I’m planning on bringing this up version by version.

This PR has two lines of work in order to get a [green build on TravisCI](https://travis-ci.org/github/gnclmorais/planner/builds/743814816):
1. Upgrade `rails` gem and other directly related gems, while applying the required changes the [official guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0) points out. Some issues will show up, so those need to be dealt with as well.
2. We had Bullet previously set to raise errors on test runs if N+1 queries got detected. For some reason, several showed up after the upgrade — makes me wonder if a) this setting was not working before or b) something changed in Rails that either preloads too much or not enough data. In any case, this pull request also includes several commits that tried to address N+1 queries in order to make tests pass (even the commits that are essentially removing global variables from partials and inject locals instead). In the end, I had to disable Bullet for a couple of specific combination of model + infraction type + association.

From the top of my head, this is the list of tasks I had in mind related with this Rails upgrade:
- [x] Bump gems
- [x] Address [version changes](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0)
- [x] Fix upgrade errors
- [x] Address [Code Climate suggestions](https://codeclimate.com/github/codebar/planner/pull/1434) (the one remaining was not triggered with new logic)
- [ ] Deal with new deprecation warnings (you can see some [here](https://travis-ci.org/github/gnclmorais/planner/builds/743808806#L516))
- [ ] Adopt [new framework defaults](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-framework-defaults)
- [ ] Maybe set better configuration for Bullet error raising?
- [ ] Maybe remove ActionCable?
- [ ] Maybe remove ActionJob?

### CODE REVIEW

**Comment by despo** [comment]
@gnclmorais thanks for this PR. However I don't think we are quite prepared for an upgrade right now. 

Part of the reason is that @KimberleyCook is working on a big PR updating all of our views to use bootstrap which is higher on our priority list and we need to spend quite sometime verifying that first. Besides that we are also not comfortable with the lack of test coverage, especially of UI components and some pages that use JavaScript so we want to be able to spend sometime verifying this on staging - and we've just sorted out some issue we've had in that environment so we need to get time to sort out data for that so it's a better reflection of production.

If you are still interested in keeping this up to date we are likely to be looking into upgrading the app sometime probably around the beginning of the New Year.

However, I would be happy to merge some of the improvements that you have made in this PR if you open those changes as a new PR. Let me know if you are interested and I'll try to make sometime this week to go through and leave a note on them.

**Comment by gnclmorais** [comment]
Hey @despo! Thanks for being honest, no problem about what you said. 🙂 I had the impression that upgrading Rails was high on our list, but I guess I was wrong. Is there a place where I can see our priorities, so that I can better align with them?

I’m interested to keep this pull request as updated as possible and I’m happy to cherry-pick some of the changes here into separate PRs! I’ll do it sometime this week. 👌

**Comment by despo** [comment]
@gnclmorais https://github.com/codebar/planner/labels/high-priority is a good place to look. 

https://github.com/codebar/planner/issues/1317 is a recurring issue for the Monthlies team and I *think* it's relatively easy to resolve, so that may be a good place to start.

**Comment by gnclmorais** [comment]
I moved the non-Rails-upgrade related work into a different PR, let me know what you think: https://github.com/codebar/planner/pull/1440

I’ll look into [`high-priority`](https://github.com/codebar/planner/labels/high-priority) and #1317, thanks! 👀

**Pull request closed without merging**
