### PR TITLE
Show total number of spots in workshop invitation

### PR DESCRIPTION
**Pull request by legoscia**
I thought it would be nice for registered attendees to see the total number of spots available at the workshop, to give an idea of how full the workshop is and whether it's worth trying to invite more people.

What do you think?

### CODE REVIEW

**Comment by matyikriszta** [comment]
@legoscia I think this is a great idea, could you post a screenshot into this thread showing us how this looks like in the site?

**Comment by legoscia** [comment]
It looks like this:

image

**Comment by notapatch** [comment]
Hello @legoscia 

Yeah, that has been fixed. You need to rebase your change on top of the latest code.
When you've done it [this file which is causing the problem ](https://github.com/legoscia/planner/blob/show-number-of-spots/.travis.yml).

 [Will look like this one](https://github.com/codebar/planner/blob/master/.travis.yml).... 

Key line is: `dist: xenial`

**Comment by legoscia** [comment]
Seems to have worked. Thanks @notapatch !

**Pull request merged**
