### PR TITLE
[Rubocop] Layout

### PR DESCRIPTION
**Pull request by notapatch**
It's those layouts again. This is all but a couple. I can squash if you like or keep as you wish.

### CODE REVIEW

**Comment by notapatch** [comment]
@matyikriszta  ready for review

**Comment by matyikriszta** [comment]
@notapatch can this be rebased + squashed please? It has a merge conflict in there plus would be good to be one commit.

**Comment by notapatch** [comment]
on it!

**Comment by notapatch** [comment]
@matyikriszta squashed and rebased.

**Pull request merged**
