### PR TITLE
Add German translations to app #745

### PR DESCRIPTION
**Pull request by janhohner**

### CODE REVIEW

**Comment by matyikriszta** [comment]
hi @janhohner, thank you so much for contributing these translations, we have started

**Comment by matyikriszta** [comment]
@janhohner could you rebase this against master so we can merge in?

**Comment by janhohner** [comment]
@matyikriszta I have already pasted the whole translation into https://crowdin.com/project/codebar because @khamiltonuk asked me so - I thought this would then merge the changes? Am I wrong?

**Comment by matyikriszta** [comment]
@janhohner great, and yes, that means that the changes will be merged in. If all the changes have been moved to crowdin this PR can be closed. Thank you once again for your contribution.

**Comment by janhohner** [comment]
Yes, I added everything there too :)

My pleasure! I came across this issue as part of Hacktoberfest and thought this a worthy cause to contribute. I really like what you're doing :)

**Pull request closed without merging**
