### PR TITLE
Pairing Spreadsheet

### PR DESCRIPTION
**Pull request by MarckK**

### CODE REVIEW

**Comment by matyikriszta** [comment]
@MarckK what's the status of this PR? It's looking good so far. Is this ready for review or are you still working on it?

**Comment by MarckK** [comment]
Hi @matyikriszta,

Thanks for the comment! Yeah, it's in pretty good shape. The functionality is all there and working. 

But not tested. Most of the work is being done with remote APIs, so likely we need some integration tests, which might be a bit heavy. What do you think? If you have any specific opinions on how this should be done, please let me know!

**Comment by MarckK** [comment]
Hi @matyikriszta and @despo,
This can be merged in now.

**Comment by daverick** [comment]
Hi @matyikriszta @MarckK,

Will this PR be approved and merged in the near future?

We have a project in Barcelona chapter to work with our student on enhancing the pairing process codebar/barcelona#36 . 

We could use what is in this PR or start form scratch.

We won't start until September but it would be fine to have a clear state of where we are starting from.

**Comment by matyikriszta** [comment]
@MarckK I'm happy to merge this, could you do a rebase first to fix the merge conflict?

**Pull request closed without merging**
