### PR TITLE
Prefer symbols as procs

### PR DESCRIPTION
**Pull request by notapatch**
- mail(mail_args(memeber, subject), &:html.to_proc)
  - default rubocop style
  - rubocop --only Style/SymbolProc

### CODE REVIEW

**Comment by notapatch** [comment]
So codeclimate is pointing out a chance to refactor common code blocks in ActionMailer which are where these Rubocop fixes have occurred. While that is true we would be better served waiting till we get to Rails 5.1 which introduced the Rails way of drying ActionMailer - [parametized mailers ](https://guides.rubyonrails.org/5_1_release_notes.html#parameterized-mailers)

**Comment by matyikriszta** [comment]
@notapatch could you give this a rebase when you get a chance?

**Comment by matyikriszta** [comment]
> How about now? I clicked "update" button and I think that rebases it but I don't know how to verify.

The Update button does a merge (I prefer rebasing but it's not big deal). Seems like some codeclimate issues surfaced now 🤔

**Comment by notapatch** [comment]
RE: merge - cool I didn't know that. I prefer rebase. I'll avoid the button from now on.  

---

We talking about these new fixes?

Screenshot 2019-10-24 at 16 25 07

The error is a penalization of success - by reducing the number of lines and making them the same it's now realising that the blocks of code could be refactored.

The proper refactoring of the mailer can only happen in Rails 5.1 where [parametized mailers](https://guides.rubyonrails.org/5_1_release_notes.html#parameterized-mailers) - should shrink the mailer code dramatically. (I am assuming that Rails 5.1 is a goal?)

AKA ... We should prefer duplication until the new tool becomes available.

**Comment by matyikriszta** [comment]
@notapatch yes, Rails 5.1 is a goal eventually. In that case I'll mark those issues as WONTFIX in codeclimate with the understanding that these methods will be refactored once we get to 5.1.

**Comment by notapatch** [comment]
Hopefully that's it? I managed to delete the branch so updating the branch wasn't straightforward.

**Comment by matyikriszta** [comment]
@notapatch it did update, just waiting on checks to pass (fingers crossed for blasted coveralls).

**Comment by notapatch** [comment]
Hehe -0.02... could be worse some people get a -0.00% error.

**Pull request merged**
