### PR TITLE
Event component tweaks

### PR DESCRIPTION
**Pull request by zaccolley**
This updates the look of the event component across the site.
It also updates the link styling across the site.

Before:

image

After:

image

### CODE REVIEW

**Comment by KimberleyCook** [comment]
What now happens to the `manage` button if you're an organiser?

screen shot 2017-08-19 at 19 52 01

**Comment by zaccolley** [comment]
They go to the side of the title. I'll get you a screenshot tomorrow.

I also want to change the links back as I'm not convinced they are different enough from the body text. Will submit a better solution as a separate PR.

**Comment by KimberleyCook** [comment]
@zaccolley cheers, and yeah I'm happy to change links as the dotted pink underline isn't that nice but not sure this solution makes it clear that it's a link.

**Comment by zaccolley** [comment]
image

Have updated the links again to make them more blue so they stand out. Here's a screenshot of what it looks like to get attending or see manage button.

**Comment by zaccolley** [comment]
can I get a review of this too @KimberleyCook ? thanks!

**Comment by KimberleyCook** [comment]
I'm not 100% sure these now look like links, @matyikriszta what do you think?

**Comment by zaccolley** [comment]
I'm going to remove the links change and then submit that a seperate PR

**Comment by zaccolley** [comment]
image

OK - have reverted the link changes, here's what it looks like now

**Comment by zaccolley** [comment]
closing cause i dont want to have to keep this synced with master

**Comment by zaccolley** [comment]
@despo Need to fix this PR but in terms of the style what do you think?

**Comment by despo** [comment]
Hi @zaccolley - I had a look at this last night and overall it looks good, however some of the partials for  the event types have not been converted - the event below specifically is of type `Meeting` so they need to be updated to.

(Excuse the bad screenshot, no images on local)
screen shot 2018-05-01 at 08 09 14

**Pull request closed without merging**
